ДЗ#9. Рефакторинг на Dagger2
alex-sus/App65 pull request #11
Opened 2021-04-27 17:35 UTC by alex-sus

В качестве DI фрэймворка использовать Dagger 2

В задании следует использовать различные Scopes:
@Singleton для зависимостей предоставляемых на время жизни всего приложения
@ContactsListScope - для зависимостей предоставляемых на время жизни Presenter/ViewModel экрана списка контактов
@ContactsDetailsScope - для зависимостей предоставляемых на время жизни Presenter/ViewModel экрана деталей контактов

Зависимости между компонентами через subcomponents

2021-04-27 17:37 UTC, alex-sus commented
Скажу сразу: внедрение вьюмоделей делал по этой статье:
https://medium.com/@vit.onix/dagger2-viewmodel-81d4cd59f642

2021-04-27 18:21 UTC, KalimullinIlnaz requested changes
У тебя проект собирается?

2021-04-27 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/di/app/AppModule.kt
> +    fun provideApplicationContext() = application
Всегда нужно задавать конкретный тип, который возвращает провайд метод метод

2021-04-27 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/di/app/AppModule.kt
> +    fun provideContactRepository() = ContactRepository(application.contentResolver)
возвращаемым значением провайд метода должен  интерфейс данного репозитория

2021-04-27 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/model/ContactRepository.kt
> +class ContactRepository(val contResolver: ContentResolver) {
переменная private
репозиторий нужно закрыть абстракцией, то есть создать какой то интерфейс, который будет определять поведение данного репозитория

2021-04-27 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/di/scope/ContactsListScope.kt
> +annotation class ContactsListScope
скоупы лучше положить в тот же пакет, в котором лежит его модуль

2021-04-27 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        (activity?.application as AppDelegate)
requireActivity()

2021-04-27 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        (activity?.application as AppDelegate)
requireActivity()

2021-04-27 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ViewModelFactory.kt
> +class ViewModelFactory
форматирование нужно исправить
```
class ViewModelFactory @Inject constructor(
    private val viewModels: MutableMap<Class<out ViewModel>, Provider<ViewModel>>
) : ViewModelProvider.Factory {
```

2021-04-27 18:31 UTC, alex-sus commented
> У тебя проект собирается?

Собирается и нормально работает на смартфоне, а что?

2021-04-27 18:34 UTC, KalimullinIlnaz commented
![image](https://user-images.githubusercontent.com/63044917/116294135-a9337c00-a7a8-11eb-8e75-4f59d79d0953.png)
точно все запушил?

2021-04-27 18:46 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/di/viewmodel_factory/ViewModelFactoryModule.kt
> +    abstract fun bindViewModelFactory(factory: ViewModelFactory): ViewModelProvider.Factory
Чтобы собралось, здесь временно закомментируй  @Singleton
Потом, когда соберется, можно будет вернуть обратно.

2021-04-27 18:49 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/di/viewmodel_factory/ViewModelFactoryModule.kt
> +    abstract fun bindViewModelFactory(factory: ViewModelFactory): ViewModelProvider.Factory
вернул - сломалось

2021-04-27 19:00 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/di/viewmodel_factory/ViewModelFactoryModule.kt
> +    abstract fun bindViewModelFactory(factory: ViewModelFactory): ViewModelProvider.Factory
Ну вообще-то в статье синглтона там не было, это я сам его придумал )
Наверное нужно его убрать.
Хотя у меня после первой компиляции, когда классы даггера уже сформировались, дальше компилируется и с этим синглтоном нормально.

2021-04-27 19:07 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/di/app/AppModule.kt
> +    fun provideContactRepository() = ContactRepository(application.contentResolver)
А как его назвать?

2021-04-27 19:31 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/di/app/AppModule.kt
> +    fun provideApplicationContext() = application
Сделано

2021-04-27 19:31 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/di/app/AppModule.kt
> +    fun provideContactRepository() = ContactRepository(application.contentResolver)
Значит будет ContactRepositoryInterface

2021-04-27 19:34 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/model/ContactRepository.kt
> +class ContactRepository(val contResolver: ContentResolver) {
Закрыл

2021-04-27 19:34 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/di/scope/ContactsListScope.kt
> +annotation class ContactsListScope
Сделано

2021-04-27 19:34 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        (activity?.application as AppDelegate)
Сделано

2021-04-27 19:34 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        (activity?.application as AppDelegate)
Сделано

2021-04-27 19:34 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/viewmodel/ViewModelFactory.kt
> +class ViewModelFactory
Сделано

2021-04-27 19:35 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/di/viewmodel_factory/ViewModelFactoryModule.kt
> +    abstract fun bindViewModelFactory(factory: ViewModelFactory): ViewModelProvider.Factory
Короче я его убрал

2021-04-28 16:41 UTC, KalimullinIlnaz approved these changes

2021-04-28 17:14 UTC, merged