ДЗ#10. Clean Architecture
alex-sus/App65 pull request #12
Opened 2021-05-03 19:07 UTC by alex-sus

Рефакторинг на  Clean Architecture:
- Разбить приложение на слои - gradle модули:
- Entity и Interactors/UseCases - чисто java модули: apply plugin: 'java'
- Адаптеры и интерфейсы(Presenter/ViewModel, Репозитории) и платформенный слой(Детали реализации) - android модули: apply plugin: 'com.android.library'
- Конфигурация(DI) - модуль android приложения: apply plugin: 'com.android.application'

- Следовать правилу зависимостей

2021-05-03 19:57 UTC, KalimullinIlnaz requested changes

2021-05-03 19:57 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactDetailsViewModel.kt
> +    private val contactRepository: ContactRepositoryInterface
вьюмодель должна использовать интерактор

2021-05-03 19:57 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactListViewModel.kt
>  class ContactListViewModel @Inject constructor(
аналогично здесь

2021-05-03 20:01 UTC, KalimullinIlnaz requested changes

2021-05-03 20:01 UTC, KalimullinIlnaz commented on application/src/main/java/ru/yodata/app65/di/contact/ContactDetailsModule.kt
> +    fun providesContactDetailsInteractor(repository: ContactRepository): ContactDetailsInteractor =
метод должен получать ContactRepositoryInterface

2021-05-03 20:01 UTC, KalimullinIlnaz commented on application/src/main/java/ru/yodata/app65/di/contacts/ContactListModule.kt
> +    fun provideContactListInteractor(repository: ContactRepository): ContactListInteractor =
аналогично

2021-05-03 20:01 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/ContactDetailsFragment.kt
> +                        1000 * 60 * 60 * 24 * 366 // кол-во миллисекунд в високосном году
вынести в константу это значение

2021-05-04 06:21 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactDetailsViewModel.kt
> +    private val contactRepository: ContactRepositoryInterface
Прохлопал я. Сделано

2021-05-04 06:22 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactListViewModel.kt
>  class ContactListViewModel @Inject constructor(
Сделано

2021-05-04 06:22 UTC, alex-sus commented on application/src/main/java/ru/yodata/app65/di/contact/ContactDetailsModule.kt
> +    fun providesContactDetailsInteractor(repository: ContactRepository): ContactDetailsInteractor =
Сделано

2021-05-04 06:22 UTC, alex-sus commented on application/src/main/java/ru/yodata/app65/di/contacts/ContactListModule.kt
> +    fun provideContactListInteractor(repository: ContactRepository): ContactListInteractor =
Сделано

2021-05-04 06:22 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactDetailsFragment.kt
> +                        1000 * 60 * 60 * 24 * 366 // кол-во миллисекунд в високосном году
Сделано

2021-05-04 16:49 UTC, KalimullinIlnaz requested changes

2021-05-04 16:49 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/ContactListFragment.kt
> +        (requireActivity().application as HasAppComponent)
сделай нулабельной проверку, а вдруг не скастится)

2021-05-04 17:12 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/ContactListFragment.kt
> +        (requireActivity().application as HasAppComponent)
аналогично в другом фрагменте

2021-05-04 17:13 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactListFragment.kt
> +        (requireActivity().application as HasAppComponent)
Что ты имеешь в виду? Как он может не скаститься?

2021-05-04 17:54 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactListFragment.kt
> +        (requireActivity().application as HasAppComponent)
Сделано

2021-05-04 17:55 UTC, KalimullinIlnaz approved these changes

2021-05-04 17:56 UTC, merged