Курсовая работа
alex-sus/App65 pull request #13
Opened 2021-05-13 15:20 UTC by alex-sus

Справочник контактов телефона с привязкой к координатам на карте + фичи на выбор из двух вариантов

Общее:

1)Приложение позволяет считать контакты из телефона, для каждого контакта позволяет задать местоположение на карте.
для задания местоположения пользователю предлагается пальцем ткнуть на карте в нужную точку

Используются карты Гугл

2) С помощью обратного геокодинга определяется адрес выбранного местоположения.
для обратного геокодинга предлагается использовать сервис яндекса
https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/About-docpage/
пример запроса
https://geocode-maps.yandex.ru/1.x/?geocode=53.215099,56.837364&format=json
В качестве сетевого транспорта предлагается использовать Retrofit + OkHttp https://square.github.io/retrofit/
В качестве сериализации/десериализации JSON предлагается использовать Gson https://github.com/google/gson

3) Полученная информация(координаты и адрес) сохраняется в БД.
В качестве ORM предлагается использовать Room https://developer.android.com/training/data-storage/room

4) Просмотр
Имеется возможность просмотра сохраненных контактов и их детальной информации.(Должно быть уже реализовано в рамках текущих ДЗ)
Имеется возможность просмотра местоположения контакта на карте в виде пина
Имеется возможность просмотра всех пинов на карте, отмасшатбированной, чтобы влезли все

На выбор:

Вариант 1:
Имеется возможность проверки, есть ли наземный маршрут между двумя контактами,
если есть - рисуется маршрут на карте, карты масштабируется, чтобы весь маршрут уместился на экране
если нет - выводится сообщение "Не удалось проложить маршрут"
предлагается использовать Google Directions https://developers.google.com/maps/documentation/directions/start?hl=ru

2021-05-13 15:27 UTC, alex-sus commented
Реализован п.1 из описания и п.3
Т.е. пользователь из фрагмента детализации контакта по нажатию кнопки открывает фрагмент карты, тыкает пальцем на карте, ставит маркер, нажимает кнопку подтверждения и координаты записываются в Room для текущего контакта. Пока не нажата кнопка подтверждения, тыкать в карту меняя расположение маркера можно сколько угодно раз. Если кнопку подтверждения не нажать, а нажать возврат обратно - изменения координат не сохранятся (останутся прежними).

2021-05-13 17:10 UTC, KalimullinIlnaz requested changes

2021-05-13 17:10 UTC, KalimullinIlnaz commented on java/src/main/java/ru/yodata/java/entities/LocatedContact.kt
> +        var address: String = ""
все переменные val, от аргументов по умолчанию тоже лучше бы избавится
в рамках твоего проекта навряд ли могут возникнуть баги, но в реальной разработки при использовании какого  нибудь автозаполнения студии или ещё чего нибудь эти поля пропустятся и возникнут неочевидные баги

2021-05-13 17:10 UTC, KalimullinIlnaz commented on java/src/main/java/ru/yodata/java/interactors/ContactLocationRepositoryInterface.kt
> +    fun getLocationDataById(contactId: String): LocationData?
все функции отвечающие за получение данных желательно делать suspend

2021-05-13 17:10 UTC, KalimullinIlnaz commented on java/src/main/java/ru/yodata/java/interactors/ContactLocationRepositoryInterface.kt
> +    fun getLocationDataById(contactId: String): LocationData?
аналогично по всему проекту

2021-05-13 17:10 UTC, KalimullinIlnaz commented on java/src/main/java/ru/yodata/java/interactors/contact/ContactDetailsModel.kt
> +        private val locRepository: ContactLocationRepositoryInterface
сокращения в названия тоже спорная штука, не сразу понятно может быть про что это, если читаешь код

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +                }?.toMutableList()
запрос к базе данных должен быть на io потоке

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +            }
аналогично здесь нужно переключить поток выполнения
также рекомендую решить уже где у тебя будет смена потока, в репозиториях или во вьюмодели при обращении к репозиторию

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +    override suspend fun getLocatedContactList(): List<LocatedContact>? {
а точно нужно получать для всех данные ещё и из телефона?
то есть на карте со всеми местоположениями при тапе на каждый маркер будет отображаться также информация сверху?

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +            deletedContactIdList.clear()
также смени контекст выполнения

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
не нужно создавать скоуп, сделай функцию suspend
здесь утечка памяти так как скоуп не кэнселится

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
аналогично здесь

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/room/entity/ContactLocationEntity.kt
> +        val address: String
жетально ещё явно задать имя поля в базе данных, хоть и рум это делает автоматически

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/room/dao/ContactLocationDao.kt
> +interface ContactLocationDao {
также все функции запроса к базе данных нужно сделать suspend

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/ContactDetailsFragment.kt
> +    private var navigateCallback: OnMapFragmentCallback? = null
нужно обнулить в onDestroyView

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/ContactMapFragment.kt
> +                                        id = curBriefContact!!.id,
нужно избавится от !!

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/ContactMapFragment.kt
> +        // TODO Здесь нужно сделать обратный геокодинг
да!)

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(locationData)
нужно ли тут синхронизации добавлять?

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(null)
аналогично здесь

2021-05-13 17:10 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +    private val locatedContactList = MutableLiveData<MutableList<LocatedContact>>()
получается ты наружу предоставляешь изменяемый список
не нужно так делать, инкапсуляция и все такое, его менять должна только модель

2021-05-14 15:28 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
А как потом эту suspend-функцию addContactLocation вызывать во фрагменте?

2021-05-14 15:35 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
Так?:
lifecycleScope.launch { contactLocationsViewModel.addLocatedContact(curLocatedContact) }

2021-05-14 16:04 UTC, alex-sus commented on java/src/main/java/ru/yodata/java/entities/LocatedContact.kt
> +        var address: String = ""
К сожалению эти поля не могут быть val, т.к. их значения необходимо менять по ходу работы.
Аргументы по умолчанию убрал

2021-05-14 16:05 UTC, alex-sus commented on java/src/main/java/ru/yodata/java/interactors/ContactLocationRepositoryInterface.kt
> +    fun getLocationDataById(contactId: String): LocationData?
Сделано

2021-05-14 16:07 UTC, alex-sus commented on java/src/main/java/ru/yodata/java/interactors/contact/ContactDetailsModel.kt
> +        private val locRepository: ContactLocationRepositoryInterface
Сделано

2021-05-14 16:07 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +                }?.toMutableList()
Сделано

2021-05-14 16:08 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +            }
Сделано.
Переключение в репозитории

2021-05-14 16:12 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +    override suspend fun getLocatedContactList(): List<LocatedContact>? {
Да, именно так и было задумано: при тапе на любой маркер, вверху экрана будет отображаться информация об этом контакте, для этого и нужен класс LocatedContact

2021-05-14 16:12 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +            deletedContactIdList.clear()
Сделано

2021-05-14 16:16 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/room/entity/ContactLocationEntity.kt
> +        val address: String
Так делают, когда нужны отличающиеся имена полей в Entity и в БД, но я за совпадающие, так меньше путаницы.

2021-05-14 16:17 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/room/dao/ContactLocationDao.kt
> +interface ContactLocationDao {
Сделано

2021-05-14 16:19 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactDetailsFragment.kt
> +    private var navigateCallback: OnMapFragmentCallback? = null
Сделано

2021-05-14 16:20 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(locationData)
Не знаю. Добавил на всякий случай

2021-05-14 16:32 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +    private val locatedContactList = MutableLiveData<MutableList<LocatedContact>>()
Но ведь я его предоставляю наружу через LiveData, а не через MutableLiveData (см. стр.54) и мне кажется снаружи его изменить нельзя.
А меняется он только во вьюмодели, да.

2021-05-14 16:40 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactMapFragment.kt
> +        // TODO Здесь нужно сделать обратный геокодинг
Значит сделаю )

2021-05-14 17:04 UTC, KalimullinIlnaz commented on java/src/main/java/ru/yodata/java/entities/LocatedContact.kt
> +        var address: String = ""
переменные нужно сделать val, небезопасно использовать изменяемые переменные в многопоточной среде, это может привести к сложно обнаруживаемым багам
Рекомендую почитать java concurrency in practice

2021-05-14 17:04 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +    override suspend fun getLocatedContactList(): List<LocatedContact>? {
хорошо

2021-05-14 17:05 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
фрагмент не должен вызывать методы репозитория, этим должна заниматься модель, то есть нужно будет делегировать ей этот вызов через вьюмодель

2021-05-14 17:06 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(locationData)
не нужно вызывать post, если ты вызываешь этот на мейн потоке

2021-05-14 17:24 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
Я это и имел в виду, что через вьюмодель, но suspend-функцию можно вызвать только из suspend-функции, сколько не делегируй. И как это здесь сделать?

2021-05-14 17:25 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +    private val locatedContactList = MutableLiveData<MutableList<LocatedContact>>()
cамо значение вью модели, да, не изменится, так как LiveData, но то что список можно менять снаружи после его предоставления не является хорошей практикой, если тебе нужно его изменять лучше создать копию.

2021-05-14 17:26 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/room/entity/ContactLocationEntity.kt
> +        val address: String
настаивать не буду, в рамках проекта проблем быть не должно

2021-05-14 17:48 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
используй скоуп вьюмодели

2021-05-14 17:59 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(locationData)
В смысле - сделать setValue(locationData)  ?

2021-05-14 18:23 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(locationData)
да или через property просто

2021-05-16 16:03 UTC, alex-sus commented on java/src/main/java/ru/yodata/java/entities/LocatedContact.kt
> +        var address: String = ""
Пользователь может многократно тыкать пальцем по карте, меняя координаты маркера, прежде чем нажать на сохранение, т.е. нужно как-то каждый раз запоминать изменившиеся координаты. И как это сделать, если поля координат будут val ?

2021-05-16 16:04 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
Сделано

2021-05-16 16:04 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
Сделано

2021-05-16 16:04 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactDetailsFragment.kt
> +    private var navigateCallback: OnMapFragmentCallback? = null
в onDetach

2021-05-16 16:05 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactMapFragment.kt
> +                                        id = curBriefContact!!.id,
Сделано

2021-05-16 16:05 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(locationData)
Сделано

2021-05-16 16:05 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        changedLocationData.postValue(null)
Сделано

2021-05-16 16:05 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +    private val locatedContactList = MutableLiveData<MutableList<LocatedContact>>()
Сделано

2021-05-16 19:22 UTC, KalimullinIlnaz commented on java/src/main/java/ru/yodata/java/entities/LocatedContact.kt
> +        var address: String = ""
постоянно создавать новый объект или делать copy от текущего изменяя только нужные поля

2021-05-16 19:27 UTC, KalimullinIlnaz requested changes

2021-05-16 19:27 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/ContactMapFragment.kt
> +                        runBlocking(Dispatchers.IO) {
в фрагменте не должно быть такого, переместить смену контекста во вью модель

2021-05-16 19:27 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactDetailsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
уже не нужно менять контекст выполнения, раз он изменятся в репозитории

2021-05-16 19:27 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
аналогично смена контекста теперь у тебя всегда будет происходить в репозитории

2021-05-16 19:29 UTC, KalimullinIlnaz requested changes

2021-05-16 19:29 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +    suspend fun getBriefContactById(contactId: String): BriefContact? =
функции вью модели не должны быть саспенд
у тебя просто будет обычная функция в которой ты пишешь
viewModelScope.launch {
interactor.getBriefContactById(contactId)
}

2021-05-17 17:24 UTC, alex-sus commented on java/src/main/java/ru/yodata/java/entities/LocatedContact.kt
> +        var address: String = ""
Сделано

2021-05-17 17:24 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/ContactMapFragment.kt
> +                        runBlocking(Dispatchers.IO) {
Переделал

2021-05-17 17:24 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactDetailsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
Сделано

2021-05-17 17:32 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
Как ни странно, несмотря на то, что в репозитории контекст меняется, но если из этого места убрать "(Dispatchers.IO)", то приложение начинает вылетать, потому что дальше во фрагменте ContactMapFragment не успевает инициализироваться переменная curLocatedContact. Как так?

2021-05-17 17:32 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +    suspend fun getBriefContactById(contactId: String): BriefContact? =
Переделал

2021-05-17 18:47 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
думаю как исправить это ты понимаешь, а почему так происходит так сразу сказать не могу, многопоточность с корутинами веселая)
посмотрю ещё, и попробую дать ответ 
продолжай пока делать

2021-05-17 18:53 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
Да вобщем-то никаких проблем нет, всё работает (если не убирать (Dispatchers.IO) )

2021-05-17 20:02 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
Диспатчер то нужно убрать, раз смена контекста есть в репозитории

2021-05-19 13:51 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
А при чем тут переменная curLocatedContact, которая находится во фрагменте, а мы смотрим на работу вьюмодели?
Во фрагменте стоит обзервер, который срабатывает, когда обновляется LiveData у списка locatedContactList.
Если приложение вылетает, это значит, что LiveData обновляется раньше, чем закончена обработка списка. 
Из за чего это может происходить? Я думаю из-за вот этой конвертации as MutableList<LocatedContact>. Список обрабатывается на IO, обновляется LiveData, срабатывает  обзервер, и только тут начинается конвертация as MutableList<LocatedContact> на ГЛАВНОМ потоке (ведь у launch ты предлагаешь убрать диспатчер IO). Поэтому и нужно у launch оставить (Dispatchers.IO), чтобы весь процесс до конца проходил на IO и только после этого обновлялась LiveData

2021-05-20 09:49 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
Сделано короче

2021-05-21 13:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
неисправлено, cкоуп все ещё меняется во вьюмодели

2021-05-27 19:01 UTC, KalimullinIlnaz approved these changes

2021-05-27 19:01 UTC, merged