Курсовая работа #2. Обратный геокодинг
alex-sus/App65 pull request #14
Opened 2021-05-19 09:36 UTC by alex-sus

Добавил обратный геокодинг от Яндекса. Подшлифовал интерфейс приложения.

2021-05-19 17:59 UTC, KalimullinIlnaz requested changes

2021-05-19 17:59 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +                return@withContext locatedContactList
от return@withContext можно избавится

2021-05-19 17:59 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +                return@withContext locatedContactList
вообще здесь можно просто написать, так как with возвращает последнюю переменную в своем блоке
```
        withContext(Dispatchers.IO) {
            //withContext(Dispatchers.IO) {
            db.contactLocationDao().getAllContactLocations()?.mapNotNull {
                // Параллельный запуск создания элементов списка locatedContactList
                withContext(Dispatchers.IO) {
                    val briefContact =
                        contactRepositoryInterface.getBriefContactById(it.contactId)
                    if (briefContact != null) {
                        LocatedContact(
                            id = it.contactId,
                            name = briefContact.name,
                            photoUri = briefContact.photoUri,
                            latitude = it.latitude,
                            longitude = it.longitude,
                            address = it.address
                        )
                    }
                    // Если для текущего идентификатора не найден контакт, это говорит
                    // о том, что этот контакт вручную удален пользователем за рамками
                    // нашего приложения. Такие ложные элементы в список не вносить,
                    // а из БД удалить.
                    else {
                        db.contactLocationDao().deleteContactLocationById(it.contactId)
                        Log.d(
                            TAG, "ContactLocationRepository: из БД удален "
                                + "несуществующий контакт id = ${it.contactId}"
                                + " address = ${it.address}"
                        )
                        null
                    }
                }
            }
        }
```

2021-05-19 17:59 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/YandexGeocoderRepository.kt
> +                ).response.geoObjectCollection.featureMember[0].geoObject.metaDataProperty
здесь обращение к конкретному индексу, возможны ситуации когда и его не будет, поэтому лучше обработать эту ситуацию

2021-05-19 17:59 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        runBlocking {
запускай через скоуп вьюмодели

2021-05-19 19:26 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +                return@withContext locatedContactList
Сделано

2021-05-19 19:27 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +                return@withContext locatedContactList
Сделано

2021-05-19 19:27 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/YandexGeocoderRepository.kt
> +                ).response.geoObjectCollection.featureMember[0].geoObject.metaDataProperty
Сделано

2021-05-19 19:27 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        runBlocking {
Сделано

2021-05-19 19:48 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        runBlocking {
не, имею ввиду стандартную конструкцию viewModelScope.launch {}

2021-05-20 09:50 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +        runBlocking {
Сделано

2021-05-22 07:25 UTC, KalimullinIlnaz approved these changes

2021-05-22 07:28 UTC, merged