Курсовая работа #3. Маршрут
alex-sus/App65 pull request #15
Opened 2021-05-26 13:46 UTC by alex-sus

Заключительный этап курсовой работы.
Для работы с картой используются 4 класса фрагментов:
Один родительский BaseMapFragment содержит нижнее меню и контейнер для запуска в нем трех дочерних фрагментов
ContactMapFragment, RouteMapFragment, EverybodyMapFragment.
Маркеры на экране всех контактов кликабельны, по щелчку отображаются данные выбранного контакта, он становится текущим для любого другого экрана.
На экране маршрута второй контакт выбирается из списка в диалоге, который вызывается кнопкой FAB.

2021-05-26 17:34 UTC, KalimullinIlnaz requested changes

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +    private fun mapLocatedContactToContactLocationEntity(locatedContact: LocatedContact)
в проде обычно пишем функцию расширение на классе LocatedContact в твоем случае
и называется она toDomain(), toData(), toDto(), в зависимости от того во что тебе нужно смапить
функции лежат в том же файле где и LocatedContact

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/GoogleDirectionsRepository.kt
> +            responce.routes[0].legs.forEach { distance = distance + it.distance.value }
responce.routes[0] опять же может быть выход за границы массива, нужно обработать
также выдели responce.routes[0] в отдельную переменную и переиспользуй ниже, не зачем постоянно обращаться к массиву

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/YandexGeocoderRepository.kt
> +            featureMemberList[0].geoObject.metaDataProperty.geocoderMetaData.address.formatted
аналогично может быть выход за границы массива

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/utils/Constants.kt
> +enum class MapScreenMode : Serializable {
enum class по умолчанию реализует Serializable

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/ContactMapFragment.kt
> +        contactMapFrag?.saveLocationFab?.setOnClickListener { saveChangedLocationData() }
зачем на каждое срабатывание обсервера ставить лисенер на вьюшку?

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/EverybodyMapFragment.kt
> +            curLocatedContact = locatedContactList.first { it.id == curContactMarker.snippet }
а может не найти элемент с таким id?

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/EverybodyMapFragment.kt
> +        }
немного непонятно, зачем идти по циклу
получается же данные последнего из списка запишутся, может сразу его возьмем?

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +    val addRouteDestinationFabListener = View.OnClickListener {
приватная

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +    val setSecondContactListener = DialogInterface.OnClickListener { _, which ->
приватная

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +        routeMapViewModel.getContactRouteDecodedDetails()
думаю его нужно перенести в onViewCreated

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +        private val listener: DialogInterface.OnClickListener
Передавать через аргументы, также вынести в отдельный класс сам фрагмент, не зачем и без того большой класс раздувать этим

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +                changedLocationData.postValue(
думаю postValue вообще не нужно в твоем случае, попробуй от него избавится во вью моделях

2021-05-26 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/RouteMapViewModel.kt
> +                        .addAll(PolyUtil.decode(encodedRoutePolyline)),
операция декодинга сложная, проведи ее на дефолт диспатчере

2021-05-26 17:35 UTC, KalimullinIlnaz commented
Также наверно нужно сменить таргет ветку, ты же этот функционал собираешься в ветку с курсовой сначала влить, а уже ее потом в main?

2021-05-27 17:03 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/RouteMapViewModel.kt
> +                        .addAll(PolyUtil.decode(encodedRoutePolyline)),
Это как? Чтобы запустить withContext(Dispatchers.IO) нужно всю функцию decodeRouteDetails во вьюмодели сделать suspend, а вроде во вьюмодели не должно быть suspend функций

2021-05-27 17:08 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/utils/Constants.kt
> +enum class MapScreenMode : Serializable {
> Также наверно нужно сменить таргет ветку, ты же этот функционал собираешься в ветку с курсовой сначала влить, а уже ее потом в main?

Да, я опять забыл указать правильный таргет. Как кстати его поменять?

2021-05-27 17:09 UTC, alex-sus commented
> Также наверно нужно сменить таргет ветку, ты же этот функционал собираешься в ветку с курсовой сначала влить, а уже ее потом в main?

Да, я опять забыл поменять ветку. Как кстати ее поменять?

2021-05-27 17:14 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +    private fun mapLocatedContactToContactLocationEntity(locatedContact: LocatedContact)
Эту функцию не получится положить в файл с LocatedContact, он же в домене, а у функции на выходе тип ContactLocationEntity - относится к Room.
Всё, что смог - переименовать ее в mapLocatedContactToDatabase

2021-05-27 17:14 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/GoogleDirectionsRepository.kt
> +            responce.routes[0].legs.forEach { distance = distance + it.distance.value }
Сделано

2021-05-27 17:15 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/YandexGeocoderRepository.kt
> +            featureMemberList[0].geoObject.metaDataProperty.geocoderMetaData.address.formatted
Так это уже было, там уже стоит проверка: featureMemberList.isNotEmpty() означает, что хотя бы 1 элемент у списка точно есть

2021-05-27 17:15 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/utils/Constants.kt
> +enum class MapScreenMode : Serializable {
Сделано

2021-05-27 17:17 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/ContactMapFragment.kt
> +        contactMapFrag?.saveLocationFab?.setOnClickListener { saveChangedLocationData() }
Этот обзервер срабатывает всего 1 раз: список контактов грузится 1 раз и не меняется в этом фрагменте

2021-05-27 17:18 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/EverybodyMapFragment.kt
> +            curLocatedContact = locatedContactList.first { it.id == curContactMarker.snippet }
Не может не найти, потому что значение снипета присваивалось из этого списка, а список в этом фрагменте не меняется

2021-05-27 17:19 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/EverybodyMapFragment.kt
> +        }
Переделал на стандартную функцию

2021-05-27 17:19 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +    val addRouteDestinationFabListener = View.OnClickListener {
Сделано

2021-05-27 17:19 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +    val setSecondContactListener = DialogInterface.OnClickListener { _, which ->
Сделано

2021-05-27 17:21 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +        routeMapViewModel.getContactRouteDecodedDetails()
Он уже был там у меня и это приводило к крэшу при повороте экрана, потому что идет обращение к карте, а карта еще не успела нарисоваться

2021-05-27 17:21 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/RouteMapFragment.kt
> +        private val listener: DialogInterface.OnClickListener
Сделано

2021-05-27 17:21 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/ContactLocationsViewModel.kt
> +                changedLocationData.postValue(
Сделано

2021-05-27 17:33 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +    private fun mapLocatedContactToContactLocationEntity(locatedContact: LocatedContact)
а если положить в ContactLocationEntity?

2021-05-27 17:34 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/ContactMapFragment.kt
> +        contactMapFrag?.saveLocationFab?.setOnClickListener { saveChangedLocationData() }
все равно вынеси, здесь нет взаимодействия с теми данными, что приходят в обсервере

2021-05-27 18:00 UTC, KalimullinIlnaz requested changes

2021-05-27 18:00 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/viewmodel/RouteMapViewModel.kt
> +                    distanceString = "${"%.1f".format(0.001 * routeDistance)} km",
0.001 - магическое число, нужно в понятную константу вынести

2021-05-27 18:33 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/data/repository/ContactLocationRepository.kt
> +    private fun mapLocatedContactToContactLocationEntity(locatedContact: LocatedContact)
Сделано

2021-05-27 18:33 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/RouteMapViewModel.kt
> +                        .addAll(PolyUtil.decode(encodedRoutePolyline)),
Сделано

2021-05-27 18:39 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/viewmodel/RouteMapViewModel.kt
> +                    distanceString = "${"%.1f".format(0.001 * routeDistance)} km",
Сделано

2021-05-27 18:55 UTC, KalimullinIlnaz approved these changes

2021-05-27 18:57 UTC, merged