ДЗ#12. Анализ кода, CI и курсовая
alex-sus/App65 pull request #17
Opened 2021-06-20 15:23 UTC by alex-sus

Внедрить статический анализ кода:
1. Требуется внедрить в проект автоматическую проверку статическим анализатором detekt. Запустить проверку и поправить все предупреждения, которые будут найдены в проекте.
2. Требуется внедрить линтер ktlint. Запустить проверку и поправить все предупреждения, которые будут найдены в проекте.

Настроить CI на основе Travis CI или Actions (от Github)

Нужно настроить такой pipeline:
- Прогон статических анализаторов: detekt, ktlint
- Сборка проекта
- Прогон тестов junit
pipeline должен срабатывать на любой Pull Request и изменения в Pull Request'е

2021-06-20 18:19 UTC, KalimullinIlnaz requested changes

2021-06-20 18:19 UTC, KalimullinIlnaz commented on .travis.yml
> +  - ./gradlew ktlint
не доделал задание, на ci прогоняется только часть необходимых проверок

2021-06-20 18:19 UTC, KalimullinIlnaz commented on library/src/main/java/ru/yodata/library/view/map/BaseMapFragment.kt
> +    private lateinit var mapMenuView: BottomNavigationView
вьюху нужно обнулить в onDestroyView

2021-06-20 21:09 UTC, alex-sus commented on library/src/main/java/ru/yodata/library/view/map/BaseMapFragment.kt
> +    private lateinit var mapMenuView: BottomNavigationView
сделано

2021-06-21 09:50 UTC, KalimullinIlnaz approved these changes

2021-06-21 09:55 UTC, merged