ДЗ#2. Список контактов и Детали контакта
alex-sus/App65 pull request #3
Opened 2021-03-06 21:06 UTC by alex-sus

### Домашнее задание 2 - исправлено
Необходимо реализовать Single Activity приложение списка контактов с двумя фрагментами: "Список контактов" и "Детали контакта"
Скриншоты результатов:
Первый экран:
![Screenshot_2021-03-06-01-19-13-255_ru yodata app65](https://user-images.githubusercontent.com/79583896/110179498-98f2c680-7e21-11eb-8b86-c91bae2b4afd.jpg)

Альбомная ориентация:
![Screenshot_2021-03-06-01-19-33-281_ru yodata app65](https://user-images.githubusercontent.com/79583896/110179520-a27c2e80-7e21-11eb-9fb3-f286f5c35b77.jpg)

Второй экран:
![Screenshot_2021-03-06-01-19-47-613_ru yodata app65](https://user-images.githubusercontent.com/79583896/110179750-0c94d380-7e22-11eb-9754-0168bdbf6abe.jpg)

Альбомная ориентация:
![Screenshot_2021-03-06-01-20-10-142_ru yodata app65](https://user-images.githubusercontent.com/79583896/110179782-1ae2ef80-7e22-11eb-9020-383c65e08b76.jpg)

Прокрутка экрана:
![Screenshot_2021-03-06-01-21-03-155_ru yodata app65](https://user-images.githubusercontent.com/79583896/110179843-33eba080-7e22-11eb-8070-2200dc6eb628.jpg)

**Сгенерированы цвета:**
colorPrimary = #b1486f
colorAccent = #f06577

2021-03-07 08:44 UTC, KalimullinIlnaz requested changes

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/Settings.kt
> +object Settings {
давай его лучше Const назовем или Constants, так больше соотвествовать будет

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/Settings.kt
> +    val contactList: ArrayList<MyContact> = arrayListOf(MyContact(
val contactList: List<MyContact> = listOf(...) здесь лучше сделать так, то есть использовать более общий тип

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    // Инициализация View Binding
от комментариев также избавься, всё и без этого понятно
upd: ниже тоже

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private val detailsFrag get() = _detailsFrag!!
здесь можно использовать одну переменную

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        arguments?.let {
используй requireArguments(), тогда можно будет избавится от let

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        return inflater.inflate(R.layout.fragment_contact_details, container, false)
так у тебя инфлейтинг уже здесь `class ContactDetailsFragment : Fragment(R.layout.fragment_contact_details) {`
, переопределять этот метод не нужно

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        (activity as AppCompatActivity).supportActionBar!!.title =
старайся все же избегать !!, в какой то мере можно сказать нулбезопасность теряешь
рекомендую почитать kotlin in action

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/model/MyContact.kt
> +        val id: Int,
id сделай тоже стрингом

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private var _listFrag: FragmentContactListBinding? = null
к этому фрагменту замечания аналогичны

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        fun newInstance(contactId: Int) =
CONTACT_ID правильней будет держать в этом компаньоне, а не в settings

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        fun newInstance(contactId: Int) =
не понимаю зачем тебе передавать id конкретного контакта в лист фрагментов

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
от констрейнта тут можно избавится

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +    android:padding="8dp"
все размеры нужно вынести в ресурсы, файл dimens.xml

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView3"
нужно везде делать понятные названия

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView4"
название

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView5"
название

2021-03-07 08:44 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView6"
название

2021-03-07 18:51 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/Settings.kt
> +object Settings {
Сделано

2021-03-07 18:51 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/Settings.kt
> +    val contactList: ArrayList<MyContact> = arrayListOf(MyContact(
Сделано

2021-03-07 18:52 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    // Инициализация View Binding
Сделано

2021-03-07 18:55 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private val detailsFrag get() = _detailsFrag!!
Можно использовать одну, но тогда придется каждый раз обращаться к ней через !! :  detailsFrag!! , иначе Андроид Студио будет светить ошибку.
Оставил пока как есть.

2021-03-07 18:56 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        arguments?.let {
Сделано

2021-03-07 18:57 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        return inflater.inflate(R.layout.fragment_contact_details, container, false)
Это Андроид Студио генерирует автоматически.
Убрал.

2021-03-07 19:00 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        (activity as AppCompatActivity).supportActionBar!!.title =
Я стараюсь избегать и про нулбезопасность читал, но здесь без !! Андроид Студио светит ошибку.
Или напиши, как по другому достучаться во фрагменте до toolbar.
Оставил как есть.

2021-03-07 19:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/model/MyContact.kt
> +        val id: Int,
Сделано

2021-03-07 19:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private var _listFrag: FragmentContactListBinding? = null
Сделано

2021-03-07 19:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        fun newInstance(contactId: Int) =
Сделано

2021-03-07 19:04 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        fun newInstance(contactId: Int) =
Это временное решение, пока нет Recycler View. Потом это будет убрано и переделано под него.
Пока оставил как есть.

2021-03-07 19:05 UTC, alex-sus commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
Вместо констрейта поставил Linear Layout.
Сделано

2021-03-07 19:05 UTC, alex-sus commented on app/src/main/res/layout/fragment_contact_details.xml
> +    android:padding="8dp"
Сделано

2021-03-07 19:06 UTC, alex-sus commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView3"
Сделано

2021-03-07 19:06 UTC, alex-sus commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView4"
Сделано

2021-03-07 19:06 UTC, alex-sus commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView5"
Сделано

2021-03-07 19:06 UTC, alex-sus commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:id="@+id/textView6"
Сделано

2021-03-07 19:25 UTC, KalimullinIlnaz requested changes

2021-03-07 19:25 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private val detailsFrag get() = _detailsFrag!!
так комменты сам не ресолвь, это я делаю
ещё раз, сделай это все в одной переменной, обращайся через ?

2021-03-07 19:25 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        (activity as AppCompatActivity).supportActionBar!!.title =
аналогично через ?

2021-03-07 19:25 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private var _listFrag: FragmentContactListBinding? = null
Аналогично

2021-03-07 19:27 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        fun newInstance(contactId: Int) =
здесь совершенно не причем ресайклер вью, тебе не нужен id контакта, когда ты создаешь этот фрагмент, для наглядности можешь добавить ещё пару контактов

2021-03-07 19:30 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        fun newInstance(contactId: Int) =
здесь и jvm ставит в целом то не особо нужен, но можно и оставить

2021-03-07 19:41 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private val detailsFrag get() = _detailsFrag!!
cделай одну переменую и обращайся через ?

2021-03-07 19:41 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        (activity as AppCompatActivity).supportActionBar!!.title =
Обращайся через ?

2021-03-07 19:41 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private var _listFrag: FragmentContactListBinding? = null
аналогично про ?

2021-03-07 20:45 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private val detailsFrag get() = _detailsFrag!!
Если я так сделаю, то не смогу использовать with(detailsFrag), потому что нельзя написать with(detailsFrag?)
Сейчас у меня так, всё четко и красиво:
with (detailsFrag) {
                fullNameTv.text = name
                phone1Tv.text = phone1
                phone2Tv.text = phone2
                email1Tv.text = email1
                email2Tv.text = email2
                descriptionTv.text = description
            }
            А если убрать вторую переменную и применять ?, то придется писать так (обрати внимание, что вопросительных знаков по два в каждой строчке):
            detailsFrag?.fullNameTv?.text = name
            detailsFrag?.phone1Tv?.text = phone1
            detailsFrag?.phone2Tv?.text = phone2
            detailsFrag?.email1Tv?.text = email1
            и т.д.
            Это что - лучше? 
            Чем плоха вторая переменная, если она позволяет сделать проще?
            Или я чего-то не понимаю?
            Еще раз скажи: убирать вторую переменную или можно оставить?

2021-03-07 21:07 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private val detailsFrag get() = _detailsFrag!!
apply или let можешь использовать, не только with же есть в scope functions kotlin-а
почитай ещё про них

2021-03-07 21:09 UTC, KalimullinIlnaz requested changes

2021-03-07 21:09 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private lateinit var mCallback: OnContactListCallback
его бы в onDetach ещё обнулить бы

2021-03-08 17:38 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private val detailsFrag get() = _detailsFrag!!
Продолжим.
Сделано через apply.

2021-03-08 17:38 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        (activity as AppCompatActivity).supportActionBar!!.title =
Сделано через ?

2021-03-08 17:39 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private var _listFrag: FragmentContactListBinding? = null
Сделано

2021-03-08 17:40 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        fun newInstance(contactId: Int) =
Сделано.
ContactListFragment изменен и больше не получает contactId извне.

2021-03-08 17:43 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private lateinit var mCallback: OnContactListCallback
Не понял, что нужно обнулить в onDetach?
listFrag обнуляется в onDestroyView, как рекомендует Гугль

2021-03-08 17:57 UTC, KalimullinIlnaz requested changes

2021-03-08 17:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private lateinit var mCallback: OnContactListCallback
я указал на переменную колбэка, ее нужно обнулить

2021-03-08 17:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        const val CONTACT_ID = "id"
private

2021-03-08 17:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private var contactId: String = ""
здесь можно так написать
```
private val contactId: String by lazy {
requireArguments().getString(CONTACT_ID, "")
}
```
cледовательно и смысла переопределять метод onCreate не будет

2021-03-08 18:18 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private lateinit var mCallback: OnContactListCallback
Для этого mCallback придется сделать nullable с соответствующим обращением к ней.
Делать?

2021-03-08 18:25 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private lateinit var mCallback: OnContactListCallback
Да, делай

2021-03-08 18:37 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +    private lateinit var mCallback: OnContactListCallback
Сделал

2021-03-08 18:38 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        const val CONTACT_ID = "id"
Сделано

2021-03-08 18:40 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private var contactId: String = ""
Сделано

2021-03-08 18:55 UTC, KalimullinIlnaz commented
Хорошо сделано, можно мержить

2021-03-08 18:55 UTC, KalimullinIlnaz approved these changes

2021-03-08 19:06 UTC, alex-sus commented
Спасибо.
Вроде было написано, что мержат проверяющие. Или уже можно самостоятельно это делать?

2021-03-08 19:38 UTC, merged

2021-03-08 19:44 UTC, KalimullinIlnaz commented
Да конечно, сам мержи после моего апрува