ДЗ#3. Привязанный сервис
alex-sus/App65 pull request #4
Opened 2021-03-12 11:23 UTC by alex-sus

Необходимо написать привязанный сервис, который будет иметь публичное API предоставляющее список контактов.
Список контактов пока захардкодить в константу
Сервис должен предоставлять список контактов на другом потоке программы - т.е. должен создавать поток для загрузки списка контактов

Сценарий использования:
- Главная активность привязывается к сервису с помощью bindService
- Получает публичный интерфейс сервиса
- Предоставляет публичный интерфейс сервиса фрагментам
- Фрагменты используют публичный интерфейс сервиса для получения данных контактов

Публичный интерфейс должен иметь 2 метода:
1. Метод получения списка контактов с короткой информацией(Будет использоваться в фрагменте списка контактов) - метод должен быть асинхронным
2. Метод получения детальной информации по ID контакта(Будет использоваться в фрагменте деталей контакта) - метод должен быть асинхронным

2021-03-13 11:53 UTC, KalimullinIlnaz requested changes

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                    detailsFrag?.apply {
with излишен напиши так
curContact. detailsFrag?.apply {}

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                        fullNameTv.text = name
у тебя приложение то не крешится?) у меня твоё приложение крешится, ты сетишь данные не на мейн потоке

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +            contactList
в итоге данные у тебя все равно получаются в блокирующей манере,
ты вызываешь этот метод у себя в фрагменте и метод await у тебя блокирует всё до того момента как ты получишь данные, реализуй через callback, то есть данные загрузятся и дернется callback метод в фрагменте с данными и ты их там засетишь во вьюшки

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/OnContactLoaderServiceCallback.kt
> +    fun getScope(): CoroutineScope
этот метод будет не нужен

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/OnContactLoaderServiceCallback.kt
> +    suspend fun getContactList(): List<MyContact>
давай сущность MyContact назовем просто Contact
можно вообще создать две сущность для списка контактов и для деталей, в сущности для листа контактов будут содержаться: телефон, ид, имя
для деталей останется такая же

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        loaderCallback?.run {
тут все аналогично + старайся избегать большой вложенности, это становится трудно читать

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +            contactList
+ можешь ещё поставить delay в несколько секунд, чтобы проверить что у тебя все норм работает

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +            contactLoaderService = binder.getService()
лишняя переменная напиши просто
(service as ContactLoaderService.ContactLoaderBinder).getService()

2021-03-13 11:53 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +    }
вообще это можно написать более функционально
```
suspend fun getContactById(contactId: String) = coroutineScope.async {
            contactList.last { it.id == contactId }
        }.await()
   
```

2021-03-13 13:58 UTC, alex-sus commented
Привет, Ильназ!
Посмотри, пожалуйста в нашей группе в Телеграме - я там написал заметку о проблеме с анбиндингом при повороте экрана.

2021-03-13 14:13 UTC, KalimullinIlnaz commented
Привет, меня там нет, перешлю их тогда мне в телеграм ikalimullin

2021-03-13 15:00 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                    detailsFrag?.apply {
К сожалению так не получается - светит ошибку, curContact не знает, что такое detailsFrag

2021-03-13 15:09 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/service/OnContactLoaderServiceCallback.kt
> +    suspend fun getContactList(): List<MyContact>
Название Contact вроде занято где то в менеджере контактов? Поэтому я и сделал MyContact 

Не понял для чего плодить сущности, если данные в них совпадают?

2021-03-13 15:19 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +    }
Сделано

2021-03-13 15:20 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +            contactLoaderService = binder.getService()
Сделано.

2021-03-13 15:21 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                        fullNameTv.text = name
Да.
Обернул вывод на экран в activity?.runOnUiThread {}
Сделано

2021-03-13 15:24 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/OnContactLoaderServiceCallback.kt
> +    suspend fun getContactList(): List<MyContact>
Неважно занято или нет,
По поводу "для чего плодить сущности", окей сейчас можешь оставить, я было сориентировался на следующее задание, май бэд, в котором это решение было бы удачным, на данном задании смысла нет.

2021-03-13 15:27 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +            contactList
Блокировки не происходит, ведь я использую корутины, которые по определению не блокируют, но чтобы не смущать я убрал await, заменив на withContext
Колбек здесь не нужен, корутины для того и создавались, чтобы уйти от колбеков. Всё работает, я поставил задержку 2 секунды перед загрузкой данных - ничего не блокируется, ты можешь не ждать, когда список контактов загрузится, нажать на пустой элемент и попадешь на следующий экран.

2021-03-13 15:31 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/service/OnContactLoaderServiceCallback.kt
> +    suspend fun getContactList(): List<MyContact>
Давай подождем следующего задания, я ж не знаю его содержания, может и там перебьюсь с одной сущностью )

2021-03-13 15:43 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +            contactList
Ну да с тем что блокируется я косякнул, так как твой метод гет скоуп возвращает io диспатчер
"я использую корутины, которые по определению не блокируют", они заблокируют если будет установлен мейн диспатчер

2021-03-13 15:44 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +            contactList
Но он же не установлен )

2021-03-13 15:48 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +            contactList
но ты же написал по определению)

2021-03-13 15:51 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                    detailsFrag?.apply {
выдели тогда отдельный метод для установки данных с полученным контактом, либо прям в контексте возвращаемого значения, то есть те же скоуп функции, засеть данные

2021-03-13 16:02 UTC, KalimullinIlnaz requested changes

2021-03-13 16:02 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                activity?.runOnUiThread {
requireActivity() 
либо можно использовать ktx, раз уж на корутинах пишешь,
если не ошибаюсь это вот эта либа androidx.lifecycle:lifecycle-runtime-ktx:2.3.0
в ней есть lifecycleScope он с мейн диспатчером, в нем запустишь всё

2021-03-13 16:44 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                    detailsFrag?.apply {
Вынес в отдельный метод
Сделано

2021-03-13 16:45 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        loaderCallback?.run {
Вынес в отдельный метод
Сделано

2021-03-13 16:50 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                activity?.runOnUiThread {
requireActivity()
Сделано.

2021-03-13 18:10 UTC, KalimullinIlnaz requested changes

2021-03-13 18:10 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            getScope().launch {
здесь у тебя будет утечка памяти, ты стартуешь корутину в скоупе сервиса, скоуп сервиса переживает этот экран и следовательно появляются такие утечки

2021-03-14 06:47 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            getScope().launch {
А как же тут сделать правильно?
Запустить в собственном скоупе, типа:
  CoroutineScope(Dispatchers.IO).launch {...   
  ?

2021-03-14 10:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            getScope().launch {
да

2021-03-14 18:14 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            getScope().launch {
Сделано

2021-03-14 18:56 UTC, KalimullinIlnaz requested changes

2021-03-14 18:56 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +        private lateinit var contactLoaderService: ContactLoaderService
не храни сервис в статике, это тоже утечка памяти
нужно переделать, либо через коллбеки, либо ещё как нибудь

2021-03-14 19:45 UTC, KalimullinIlnaz requested changes

2021-03-14 19:45 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +            unbindService(connection)
вернуть

2021-03-15 09:18 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +        private lateinit var contactLoaderService: ContactLoaderService
Статика убрана.
Сделано

2021-03-15 09:18 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +            unbindService(connection)
Вернул.
Сделано.

2021-03-15 16:14 UTC, KalimullinIlnaz requested changes

2021-03-15 16:14 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        coroutineScope = CoroutineScope(Job() + Dispatchers.IO)
правильней будет использовать SupervisorJob, чтобы не крешить другие корутины, если крешнится какая либо из

2021-03-15 16:14 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                catch (e: IllegalStateException) {}
если уже ловишь что то, то всегда хотя бы выводи в логи что произошло и стек трейс ошибки

2021-03-15 16:14 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        coroutineScope = CoroutineScope(Job() + Dispatchers.IO)
правильней будет использовать SupervisorJob, чтобы не крешить другие корутины, если крешнится какая либо из

2021-03-15 16:14 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                catch (e: IllegalStateException) {}
правильней будет использовать SupervisorJob, чтобы не крешить другие корутины, если крешнится какая либо из

2021-03-15 16:14 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +        coroutineScope = CoroutineScope(Job() + Dispatchers.IO)
правильней будет использовать SupervisorJob, чтобы не крешить другие корутины, если крешнится какая либо из

2021-03-15 18:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +        private lateinit var contactLoaderService: ContactLoaderService
Что-то еще?

2021-03-15 18:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        coroutineScope = CoroutineScope(Job() + Dispatchers.IO)
Сделано

2021-03-15 18:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                catch (e: IllegalStateException) {}
Сделано

2021-03-15 18:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        coroutineScope = CoroutineScope(Job() + Dispatchers.IO)
Сделано

2021-03-15 18:55 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                catch (e: IllegalStateException) {}
Здесь стек трейс.
Сделано

2021-03-15 18:55 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/service/ContactLoaderService.kt
> +        coroutineScope = CoroutineScope(Job() + Dispatchers.IO)
Сделано

2021-03-15 18:56 UTC, KalimullinIlnaz approved these changes

2021-03-15 18:56 UTC, merged