ДЗ#4. Broadcast receiver
alex-sus/App65 pull request #5
Opened 2021-03-19 18:11 UTC by alex-sus

Необходимо добавить к деталям контакта поле "День рождения" в формате "число месяц"

А так же кнопку которая будет иметь 2 состояния - "Включить напоминания" и "Выключить напоминания"
Состояние кнопки должно зависеть от того, добавлена ли уже задача в AlarmManager или нет.

При нажатии кнопки в состоянии "Включить напоминания" - должна ставиться задача на вызов вашего BroadcastReceiver'а на число в поле "День рождения" в качестве данных в Intent должен передаваться ID выбранного контакта и текст напоминания "Сегодня день рождения у $s", где $s - имя контакта
При нажатии кнопки в состоянии "Выключить напоминания" - должна производиться отмена предстоящей задачи в AlarmManager и состояние кнопки должно обновиться на "Включить напоминания"
https://developer.android.com/training/scheduling/alarms

Ваш BroadcastReceiver в свою очередь должен запустить Notification(Специальное уведомление, которое показывается в шторке уведомлений) с текстом пришедшем ему из Intent. https://developer.android.com/training/notify-user/build-notification

При нажатии пользователем на уведомление - должна запуститься активность вашего приложения, при этом должен сразу открыться экран с деталями контакта у которого день рождение, уведомление при этом должно исчезнуть из шторки уведомлений. Смотрите https://developer.android.com/reference/android/app/Activity#getIntent()

2021-03-19 18:14 UTC, alex-sus commented
Для тестирования время срабатывания аларм менеджера автоматически настраивается так, чтобы сообщение появлялось через полминуты после нажатия на кнопку

2021-03-19 20:13 UTC, KalimullinIlnaz requested changes
В целом хорошая работа, молодец

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +object BirthdayAlarmManager {
этот класс является делегатом, нужно назвать соответствующе
также этот объект стоит разместить в классе ContactDetailsFragment, так используется только в нем, его можно будет сделать приватным и вложенным и следовательно избавится как минимум от передачи контекста в каждый метод

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +class BirthdayAlarmReceiver : BroadcastReceiver() {
а где логика установки дня рождения на следующий год?

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                                    setOnCheckedChangeListener(MyCheckedChangeListener(curContact))
сделай тут через анонимный объект

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                                    setOnCheckedChangeListener(MyCheckedChangeListener(curContact))
также используй комбинацию клавиш ctrl+alt+l для автоматического форматирования кода

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +                navigateToContactDetailsFragment(curIntent.getStringExtra(CONTACT_ID)!!)
не используй !!, лучше сделай перед этим проверку на null
null safety язык все таки)

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +        if (!activityStartedByNotification) navigateTransaction.
```
 if (!activityStartedByNotification) {
navigateTransaction. addToBackStack(ContactDetailsFragment.FRAGMENT_NAME)
}
```
тяжело читается при текущем форматировании

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> -        private const val CONTACT_ID = "id"
верни, не нужно использовать одни и те же константы для разных вещей

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/Constants.kt
> +    const val LAUNCHER_START_INTENT = "android.intent.action.MAIN" // Значение интента при старте
эту константу можно держать на уровне main activity

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +                    //.setFullScreenIntent(notificationPendingIntent, true)
удали закомментированный код

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +class BirthdayAlarmReceiver : BroadcastReceiver() {
В следующем мр, сделай без тестовых данных + учитывай людей у который день рождения 29 февраля

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/App.kt
> +        notificationSound = Uri.parse("android.resource://" + packageName +
"android.resource://" в константу

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +                    contactId.hashCode(), notificationIntent, PendingIntent.FLAG_ONE_SHOT)
используй именовые атрибуты и каждый новый атрибут в новую строку
почитай котлин стайл гайды
https://kotlinlang.org/docs/coding-conventions.html#class-headers

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private lateinit var coroutineScope: CoroutineScope
напоминаю про те корутины лишние в сервисе, удали их

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +            }
зачем with? всего одна операция же в контексте этого объекта

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +            "Посмотрите напоминание!",
в строки

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val curIntent: Intent by lazy {intent}
`private val curIntent: by lazy((LazyThreadSafetyMode.NONE)) {intent}`
здесь можно написать без уточнения типа
также можно задать thread mode, по умолчания он SYNCHRONIZED и обладает не лучшей производительностью

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val activityStartedByNotification: Boolean by lazy {
аналогично всё + форматирование

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +            if (firstAppStart && !activityStartedByNotification)
```
     if (firstAppStart && !activityStartedByNotification) {
                navigateToContactListFragment()
}
```
либо в одну строчку, если длина не привышает 100 символов

2021-03-19 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +        val navigateTransaction = supportFragmentManager.beginTransaction()
в целом названия можно давать менее точные, если в текущем блоке кода нет схожих по применению или признаку переменных, то есть просто transaction

2021-03-20 06:26 UTC, alex-sus commented
> В целом хорошая работа, молодец

Спасибо на добром слове

2021-03-20 06:32 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +object BirthdayAlarmManager {
Как конкретно назвать?
Этот объект и был у меня первоначально в классе ContactDetailsFragment, я специально вынес его в отдельный файл, чтобы он был независим, мог использоваться откуда угодно (на перспективу), не загромождал ContactDetailsFragment, а так же во исполнение принципа Single Responsability (из SOLID).
Может оставим в отдельном файле?

2021-03-20 07:18 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/Constants.kt
> +    const val LAUNCHER_START_INTENT = "android.intent.action.MAIN" // Значение интента при старте
Я наоборот пытаюсь свести все константы в один файл. Здесь ладно маленький проект, а если бы в нем было 100 файлов и все константы по ним разбросаны - это запутывает.
Может оставим на месте?

2021-03-20 07:31 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +                    contactId.hashCode(), notificationIntent, PendingIntent.FLAG_ONE_SHOT)
Здесь именованные аргументы использовать не получится: не котлиновская функция. Сообщение об ошибке:
Named arguments are not allowed for non-Kotlin functions
В новую строку - пожалуйста.

2021-03-20 11:07 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +class BirthdayAlarmReceiver : BroadcastReceiver() {
Логику сделал, включая 29 февраля
Тестовые данные остались, как ты без них проверишь работу приложения?

2021-03-20 11:07 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                                    setOnCheckedChangeListener(MyCheckedChangeListener(curContact))
Сделано

2021-03-20 11:08 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +                navigateToContactDetailsFragment(curIntent.getStringExtra(CONTACT_ID)!!)
Сделано

2021-03-20 11:08 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +        if (!activityStartedByNotification) navigateTransaction.
Сделано

2021-03-20 11:08 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> -        private const val CONTACT_ID = "id"
Сделано

2021-03-20 11:08 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +                    //.setFullScreenIntent(notificationPendingIntent, true)
Сделано

2021-03-20 11:08 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/App.kt
> +        notificationSound = Uri.parse("android.resource://" + packageName +
Сделано

2021-03-20 11:09 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +                    contactId.hashCode(), notificationIntent, PendingIntent.FLAG_ONE_SHOT)
Сделано

2021-03-20 11:09 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +    private lateinit var coroutineScope: CoroutineScope
Сделано

2021-03-20 11:09 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +            }
Сделано

2021-03-20 11:09 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +            "Посмотрите напоминание!",
Сделано

2021-03-20 11:09 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val curIntent: Intent by lazy {intent}
Сделано

2021-03-20 11:09 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val activityStartedByNotification: Boolean by lazy {
Сделано

2021-03-20 11:10 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +            if (firstAppStart && !activityStartedByNotification)
Сделано

2021-03-20 11:10 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +        val navigateTransaction = supportFragmentManager.beginTransaction()
Сделано

2021-03-20 11:57 UTC, KalimullinIlnaz requested changes

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/Constants.kt
> +    const val LAUNCHER_START_INTENT = "android.intent.action.MAIN" // Значение интента при старте
Константа используется только в одном файле, смысла засорять один файл константами, которые нужны в классе нет, только мешать будет

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +fun nextFebruary29(): Calendar {
почему эту функцию вынес за объект?
она используется только в нем и должна быть приватной

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +object BirthdayAlarmManager {
AlarmManagerHelper
если на данный момент он используется только в одном файле не нужно его выносить и тп
загромождение было бы если бы эти все функции лежали в ContactDetailsFragment, а так выделил их в отдельный объект по своему функционалу, что правильно
SR при реализации которую я предлагаю не нарушается

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +class BirthdayAlarmReceiver : BroadcastReceiver() {
я уже посмотрел твою работу + я сам могу подкорректировать твой код, если захочу что либо проверить, поэтому можно не думать об этом)

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val curIntent by lazy((LazyThreadSafetyMode.NONE)) {intent}
зачем двойные скобочки вокруг LazyThreadSafetyMode.NONE?
upd мой косяк)

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                        setOnCheckedChangeListener { buttonView, isChecked ->
` detailsFrag?.remindBtn?.setOnCheckedChangeListener { buttonView, isChecked ->`
*в одну строчку*

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +        if (curContact.birthday.get(Calendar.DAY_OF_MONTH) == 29
29 - магическое число, вынеси в константу и дай понятное название

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +                && curContact.birthday.get(Calendar.MONTH) == 2) {
аналогично и здесь, хотя здесь можно использовать константы класса календаря
p.s 2 = март, в Calendar с 0 начинается нумерация месяцев

2021-03-20 11:57 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +class BirthdayAlarmReceiver : BroadcastReceiver() {
Логика установки напоминая на следующий год должна быть в ресивере, после того как отработает напоминание на текущий год

2021-03-20 11:58 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +                    contactId.hashCode(), notificationIntent, PendingIntent.FLAG_ONE_SHOT)
да... забываешь иногда про код из джавы

2021-03-20 14:31 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmReceiver.kt
> +class BirthdayAlarmReceiver : BroadcastReceiver() {
> Логика установки напоминая на следующий год должна быть в ресивере, после того как отработает напоминание на текущий год

Не понял, зачем в ресивере? Почему после того как отработает?
Я же запускаю периодический alarm, который сам будет повторяться с заданным периодом: alarmManager.setInexactRepeating()
Кроме того, AlarmManager, вообще не особо подходит для задач, повторяющихся через год. Я задавал вопрос об этом на занятии и мне посоветовали не грузиться такими подробностями, потому что задача не про AlarmManager, а про BroadcastReceiver

2021-03-20 15:27 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +object BirthdayAlarmManager {
Я сделал, как ты хочешь.
От передачи контекста это не избавило, object не имеет доступа к контексту ContactDetailsFragment и слово inner для объекта не применимо.
Сделано.

2021-03-20 15:30 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/Constants.kt
> +    const val LAUNCHER_START_INTENT = "android.intent.action.MAIN" // Значение интента при старте
Константа не может быть на уровне main activity, это применимо только для object
Поэтому я вынес ее на top level в MainActivity.
Сделано

2021-03-20 15:31 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +fun nextFebruary29(): Calendar {
Сделано

2021-03-20 15:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val curIntent by lazy((LazyThreadSafetyMode.NONE)) {intent}
Сделано

2021-03-20 15:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                        setOnCheckedChangeListener { buttonView, isChecked ->
Сделано

2021-03-20 15:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +        if (curContact.birthday.get(Calendar.DAY_OF_MONTH) == 29
Сделано

2021-03-20 15:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +                && curContact.birthday.get(Calendar.MONTH) == 2) {
Сделано

2021-03-20 17:59 UTC, KalimullinIlnaz requested changes

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +const val LAUNCHER_START_INTENT = "android.intent.action.MAIN"
private

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        const val DAY_OF_MONTH_29 = 29
private

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        private fun nextFebruary29(): Calendar {
также правильней будет разместить эту приватную функцию под той функцией, которая ее вызвала

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            if (curContact.birthday.get(Calendar.DAY_OF_MONTH) == 29
остались эти магические числа

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        fun isBirthdayAlarmOn(context: Context, curContact: Contact): Boolean {
можно написать более функционально
```
 fun isBirthdayAlarmOn(context: Context, curContact: Contact) = PendingIntent.getBroadcast(
                    context,
                    curContact.id.hashCode(),
                    Intent (context, BirthdayAlarmReceiver::class.java),
                    PendingIntent.FLAG_NO_CREATE
            ) != null
```

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val curIntent by lazy(LazyThreadSafetyMode.NONE) {intent}
в целом можно написать такую функцию чтобы не писать везде `(LazyThreadSafetyMode.NONE)`
`fun <T> unsafeLazy(initializer: () -> T): Lazy<T> = lazy(LazyThreadSafetyMode.NONE, initializer)`

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            val result: Calendar
в целом, больше замечаний у меня нет, если есть желание можно всю реализацию работы со временем переписать на java.time, которую добавили в 8 джаве

2021-03-20 17:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +object BirthdayAlarmManager {
ну да, он должен быть вложенным классом, а не объектом для ContactDetailsFragment

2021-03-20 18:01 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        private fun nextFebruary29(): Calendar {
можешь почитать книжку Роберта Мартина Чистый код. Создание, анализ и рефакторинг, там про все это описано подробно

2021-03-20 19:32 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +object BirthdayAlarmManager {
Я сделал класс, но пришлось создать  еще объект этого класса, иначе не достучаться до его методов.
Не думаю, что это вариант лучше, чем был первоначально.
Принцип "один класс - один файл" до сих пор обязателен в java.
Приходится тратить время на переделывание вполне допустимого варианта - а этого не хотелось бы.
Сделано.

2021-03-20 19:32 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +const val LAUNCHER_START_INTENT = "android.intent.action.MAIN"
Сделано

2021-03-20 19:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        const val DAY_OF_MONTH_29 = 29
Сделано

2021-03-20 19:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        private fun nextFebruary29(): Calendar {
Сделано

2021-03-20 19:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            if (curContact.birthday.get(Calendar.DAY_OF_MONTH) == 29
Сделано

2021-03-20 19:33 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +        fun isBirthdayAlarmOn(context: Context, curContact: Contact): Boolean {
Сделано

2021-03-20 19:34 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +            val result: Calendar
Нет такого желания и у меня min API = 21

2021-03-20 19:36 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val curIntent by lazy(LazyThreadSafetyMode.NONE) {intent}
Не работает. В следующей строке из-за этого перестает видеть curIntent.action
Предлагаю оставить как есть

2021-03-20 20:12 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/utils/alarmbroadcast/BirthdayAlarmManager.kt
> +object BirthdayAlarmManager {
при использовании объекта тоже создается класс, просто он синглетон, так что разницы нет особой в этом плане в текущей ситуации
Принцип один класс - один файл - я думаю здесь про публичный класс имеется ввиду, также вложенные и внутренние классы просто мимо идут при следовании этому принципу?
"Приходится тратить время на переделывание вполне допустимого варианта - а этого не хотелось бы." - весь курс по сути построен на ревью, если можно сделать лучше и правильней - стоит это сделать, я ревьювлю тебя +- как мр у ребят с проекта

2021-03-20 20:13 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    private val curIntent by lazy(LazyThreadSafetyMode.NONE) {intent}
значит сделал не то, окей оставим

2021-03-20 20:13 UTC, KalimullinIlnaz approved these changes

2021-03-20 20:25 UTC, merged

2021-03-20 20:26 UTC, alex-sus commented
Спасибо