ДЗ#5. Content provider
alex-sus/App65 pull request #6
Opened 2021-03-29 10:47 UTC by alex-sus

Необходимо реализовать загрузку контактов пользователя из поставщика контактов
В существующем методе загрузки списка контактов - получать список всех контактов пользователя из поставщика контактов
В существующем методе загрузки деталей контакта по ID - получать все необходимые данные контакта из поставщика контактов по ID

2021-03-30 13:47 UTC, KalimullinIlnaz commented
Привет, этот мр у тебя Егор проверит, у меня на этой неделе мало времени

2021-03-30 15:08 UTC, alex-sus commented
> Привет, этот мр у тебя Егор проверит, у меня на этой неделе мало времени

Привет. Ок.

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/utils/service/OnContactLoaderServiceCallback.kt
> +    suspend fun getContactList(): List<BriefContact>
Тут тоже вопрос по suspend.

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    override suspend fun getContactList(): List<BriefContact> {
Зачем тут suspend? 
getContactList не suspend функция.

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/model/Contact.kt
> +        val photo: String = "@drawable/programmer2_100"
Зачем тут строка в виде ресурсов?

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/utils/PermissionsAccessHelper.kt
> +            showIntro: Boolean)  {
Немного по кодстайлу.
Когда параметры пишут в столбик закрывающая скобка у них ставится на следующей строке. Как у тебя сделано в методе isPermissionsRequestSuccessful.

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
>                  while (!isServiceBound()) {}
while с пустым телом кажется будет больше подогревать процессор, а не делать полезную работу :) А т.к. уже скоро лето, то можно удалить, наверное.

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/utils/service/ContactLoaderService.kt
> +                     phone1 = if (phones.count() > 0) phones[0] else SHOW_EMPTY_VALUE,
- В Котилне count возвращает просто size. Т.е. можно сразу использовать метод size().
- Можно вообще упростить красиво. Сделать  `phones.getOrNull(0) ?: SHOW_EMPTY_VALUE` и так далее ниже по коду. Выглядит куда симпатичнее.

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/utils/service/ContactLoaderService.kt
> +        val contResolver = contentResolver
Можно создать отдельный класс `object` для работы с поставщиком. Назвать на подобие `ContactDataSource`. И там будет 2 метода: "дайСписок", "дайКонктакПоИд".

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/utils/PermissionsAccessHelper.kt
> +            else activity.requestPermissions(requiredPermissions, PERMISSION_REQUEST_CODE)
Можно попробовать новое АПИ использовать для разрешений.
https://developer.android.com/training/permissions/requesting#allow-system-manage-request-code

Тут вроде тоже немного про него есть:
https://www.youtube.com/watch?v=_QyufxuP4tQ

2021-03-30 19:04 UTC, ekatkov commented on app/src/main/java/ru/yodata/app65/utils/PermissionsAccessHelper.kt
> +                val dialog = IntroDialogFragment()
В принципе, можно не создавать каждый раз новый экземпляр, а вынести в переменную и проверять перед созданием на существование и на отображение `showsDialog`.

2021-03-31 10:22 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/service/OnContactLoaderServiceCallback.kt
> +    suspend fun getContactList(): List<BriefContact>
Сделано

2021-03-31 10:22 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/MainActivity.kt
> +    override suspend fun getContactList(): List<BriefContact> {
Забыл убрать после переделки.
Сделано

2021-03-31 10:23 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/model/Contact.kt
> +        val photo: String = "@drawable/programmer2_100"
Убрал

2021-03-31 10:23 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/PermissionsAccessHelper.kt
> +            showIntro: Boolean)  {
Сделано

2021-03-31 10:28 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
>                  while (!isServiceBound()) {}
Удалить нельзя, иначе приложение не переживет поворот экрана. При повороте ссылка на ibinder уничтожается, а новая вычисляется не сразу, и если не подождать, пока она создастся, будет NPE. Я подробно писал об этом в нашей группе в Телеграме

2021-03-31 10:28 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/service/ContactLoaderService.kt
> +                     phone1 = if (phones.count() > 0) phones[0] else SHOW_EMPTY_VALUE,
Сделано

2021-03-31 10:28 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/service/ContactLoaderService.kt
> +        val contResolver = contentResolver
Сделано

2021-03-31 10:38 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/PermissionsAccessHelper.kt
> +            else activity.requestPermissions(requiredPermissions, PERMISSION_REQUEST_CODE)
Не вижу принципиальной разницы для ДАННОЙ задачи. Раньше колбэк назывался строго onRequestPermissionsResult, а теперь ему можно дать любое имя и не указывать requestCode (но взамен указывать колбэк)? На мой взгляд это не то преимущество, чтобы выкидывать готовый вариант.
Может оставим как есть?

2021-03-31 12:38 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/utils/PermissionsAccessHelper.kt
> +                val dialog = IntroDialogFragment()
Сделано

2021-04-01 16:41 UTC, KalimullinIlnaz commented on app/build.gradle
> +        minSdkVersion 23
В реальных условиях так просто версию api не поднимешь, нужно выкручиваться бывает, так что не злоупотребляй этим

2021-04-01 16:41 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                remindBtn.isChecked = if (birthday != null)
нужны {} для веток if-а. плохо читается

2021-04-01 16:44 UTC, KalimullinIlnaz commented
![image](https://user-images.githubusercontent.com/63044917/113326653-06175000-932b-11eb-8bbb-70276b125db9.png)
при запуске приложения крэш

2021-04-01 16:45 UTC, KalimullinIlnaz requested changes

2021-04-01 16:45 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                val curContact = getContactList(contResolver)[60]
почему 60

2021-04-01 18:26 UTC, alex-sus commented on app/build.gradle
> +        minSdkVersion 23
Вернул 21. Поставил проверку sdk при запросе разрешений
Сделано

2021-04-01 18:27 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactDetailsFragment.kt
> +                remindBtn.isChecked = if (birthday != null)
Сделано

2021-04-01 18:31 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                val curContact = getContactList(contResolver)[60]
60 - просто взял цифру с потолка посмотреть свои контакты.
А крэш потому, что на твоем смартфоне меньше 60-ти контактов или ты запускаешь на эмуляторе.
Поставил 0.
Сделано.

2021-04-01 18:47 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                val curContact = getContactList(contResolver)[60]
На данный момент приложение работает некорректно
нужно чтобы выводился весь список контактов, который ты можешь подтянуть из бд телефона
при нажатии на какой либо из них, должна выводится детальная информация по нему
нужно доработать

2021-04-01 18:57 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                val curContact = getContactList(contResolver)[60]
Я задавал этот вопрос на занятии. Ответ был - весь список сейчас не выводить. Пока мы не прошли RecyclerView, выводить на экране один любой элемент. Можешь посмотреть запись занятия, в конце:
https://drive.google.com/file/d/1h-ZwopxibnbOfvBc9hQHv1ABmKfzl55c/view

2021-04-01 19:01 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                val curContact = getContactList(contResolver)[60]
Мда, не думал, что что-то изменится, ну ладно, тогда оставим

2021-04-01 19:02 UTC, KalimullinIlnaz approved these changes

2021-04-01 19:04 UTC, merged

2021-04-01 19:09 UTC, alex-sus commented
Спасибо за апрув!