ДЗ#7. RecyclerView и поиск
alex-sus/App65 pull request #8
Opened 2021-04-11 18:15 UTC by alex-sus

Добавить поиск по именам. Лучше использовать SearchView. Каждый новый ввод символа в SearchView - должен приводить к пере-запросу данных списка контактов из репозитория. При пустом вводе - выводится весь список контактов

Отслеживание изменений через DiffUtils. Желательно производить diff на отдельном потоке, для этого можно воспользоваться готовой реализацией адаптера - ListAdapter

Написать свою реализацию разделителей между элементами, через ItemDecorator

2021-04-12 18:15 UTC, KalimullinIlnaz requested changes

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/model/ContactRepository.kt
> +                            name = cursor.getString(CURSOR_MAIN_VALUE_COLUMN) ?: SHOW_EMPTY_VALUE
почему show? просто empty тогда уже

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    inner class ContactViewHolder(var contactRow: ContactListRowBinding)
сделай обычным классом, в этом кейсе у тебя холдер содержит ссылку на адаптер, а это не очень хорошо
также про это написано в AndroidLessonsCommonMistake

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    inner class ContactViewHolder(var contactRow: ContactListRowBinding)
contactRow сделай val и private

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
здесь уже можно вместо интерфейсов использовать лямбды

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        listFrag?.contactsRecyclerView?.apply {
вообще у contactsRecyclerView нужно ещё обнулять adapter и layoutManager в onDestroyView, но в случае view binding-а это излишне думаю

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +            addItemDecoration(ContactItemDecoration(getDrawable(context, R.drawable.divider14)!!))
избавься от `!!`

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                    Log.d(TAG, "Исключение в ContactListFragment: ")
если уж пишешь что произошла ошибка, то нужно написать так, чтобы было понятно, фрагмент может быть очень большим)
иногда небольшой комментарий полезней stackTracе

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +                    if (newFilter.contains(nameFilter.value!!)) {
избавься от `!!`

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +                        filteredList.postValue(filteredList.value?.filter {
нужно фильтровать на уровне получения данных, то есть когда идет запрос к бд
представь, что у тебя миллиард контактов и то есть ты их сначала получаешь, а потом ещё сверху фильтруешь, ну так себе получается по производительности

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +    private val nameFilter = MutableLiveData(" ") // фильтр имен, соответствующий filteredList
зачем nameFilter  live data?

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +    private val nameFilter = MutableLiveData(" ") // фильтр имен, соответствующий filteredList
да и название должно быть, что то в стиле currentFilterValue

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +            if (newFilter.isEmpty()) filteredList.postValue(contactList.value)
`filteredList.postValue(contactList.value)` в фигурные скобки

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +    private val contactList = MutableLiveData<List<BriefContact>>() // полный список контактов
здесь тоже можно избавится от live data

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_list.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
используй комбинацию ctrl + alt + l на своих файлах, удобнее и приятней читать код становится

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_list.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
![image](https://user-images.githubusercontent.com/63044917/114440174-de51a300-9bda-11eb-89ff-39af440046fd.png)
и также проставь тут галочки, когда коммитишь
они тоже про код стайл

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/res/layout/fragment_contact_list.xml
> +    android:orientation="vertical">
зачем ориентация у фрейм лаяута?

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactItemDecoration.kt
> +            if (childAdapterPosition == adapter.itemCount - 1) outRect.bottom = 0
все таки используй везде `{}` 
как по мне читается легче
также повторюсь, что можно их не ставить, если всё условие if/else влезает в одну строку, в других случаях используй фигурные скобки

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactItemDecoration.kt
> +            if (childAdapterPosition == adapter.itemCount - 1) outRect.bottom = 0
Аналогично по всему проекту

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    inner class ContactViewHolder(var contactRow: ContactListRowBinding)
https://github.com/goblinr/AndroidLessonsCommonMistakes/blob/master/%D0%9F%D0%B5%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD_%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0_%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%BE%D0%B2_%D0%BD%D0%B0_RecyclerView.md

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    private class DiffCallback : DiffUtil.ItemCallback<BriefContact>() {
можно сделать object

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    inner class ContactViewHolder(var contactRow: ContactListRowBinding)
```
    class ContactViewHolder(
        private val contactRow: ContactListRowBinding
    ) : RecyclerView.ViewHolder(contactRow.root) {
```
такое должно быть форматирование, если не влезает в одну строку

2021-04-12 18:15 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +                navigateCallback?.navigateToContactDetailsFragment(item.id)
нужно проверка на No_positon

2021-04-12 19:42 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
Не понял, какие лямбды использовать и чем плох интерфейс?

2021-04-12 19:47 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/model/ContactRepository.kt
> +                            name = cursor.getString(CURSOR_MAIN_VALUE_COLUMN) ?: SHOW_EMPTY_VALUE
show чтобы подчеркнуть, что это значение предназначено именно для показа на экране, а не просто какое-то пустое значение

2021-04-12 19:47 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +        listFrag?.contactsRecyclerView?.apply {
Я тоже так думаю

2021-04-12 19:50 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
котлин предоставляет эту функциональную возможность
это удобнее и быстрее написать, ты создаешь интерфейс реализуешь его, когда просто можешь написать как то так
val action (String) -> Unit и в месте создания написать реализацию этой функции

2021-04-12 19:52 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/model/ContactRepository.kt
> +                            name = cursor.getString(CURSOR_MAIN_VALUE_COLUMN) ?: SHOW_EMPTY_VALUE
неважно это + это слой работы с данными, но про это уже позже

2021-04-12 19:56 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
Вообще ничего не понял. Где именно я должен написать val action (String) -> Unit ?
С интерфейсом всё просто - поймал во фрагменте в onAttach и передал по эстафете. А с лямбдой как?

2021-04-12 19:59 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
class ContactListAdapter(private val action (String) -> Unit)

2021-04-12 20:13 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
Когда я так изменил заголовок, всё остальное покрасилось в красный цвет, андроид студио сошел с ума.
Сейчас ночью я что-то вообще не могу понять, в чем тут идея

2021-04-12 20:15 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
А - двоеточия не хватало... и дальше что?

2021-04-12 20:23 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
И что передается в этом String ?

2021-04-12 21:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/model/ContactRepository.kt
> +                            name = cursor.getString(CURSOR_MAIN_VALUE_COLUMN) ?: SHOW_EMPTY_VALUE
Сделано

2021-04-12 21:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    inner class ContactViewHolder(var contactRow: ContactListRowBinding)
Сделано

2021-04-12 21:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    inner class ContactViewHolder(var contactRow: ContactListRowBinding)
Сделано

2021-04-12 21:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +            addItemDecoration(ContactItemDecoration(getDrawable(context, R.drawable.divider14)!!))
Сделано

2021-04-12 21:54 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListFragment.kt
> +                    Log.d(TAG, "Исключение в ContactListFragment: ")
Сделано

2021-04-12 21:55 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +                    if (newFilter.contains(nameFilter.value!!)) {
Сделано

2021-04-12 22:00 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +                        filteredList.postValue(filteredList.value?.filter {
Ты предлагаешь при каждом введенном символе в SearchView по новой перечитывать все контакты???
У меня на смартфоне с более 200 контактами на это уходит 2-3 секунды. Ты представляешь, как тормознуто будет работать такой "поиск"? Это хорошо на эмуляторе где почти нет контактов создавать видимость работающего приложения.
Сейчас я только 1 раз получаю данные контактов и кэширую их. Зато поиск по каждому введенному символу реально быстро работает.

2021-04-12 22:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +    private val nameFilter = MutableLiveData(" ") // фильтр имен, соответствующий filteredList
Сделано

2021-04-12 22:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +            if (newFilter.isEmpty()) filteredList.postValue(contactList.value)
Сделано

2021-04-12 22:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +    private val contactList = MutableLiveData<List<BriefContact>>() // полный список контактов
Сделано

2021-04-12 22:01 UTC, alex-sus commented on app/src/main/res/layout/fragment_contact_list.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
Сделано

2021-04-12 22:02 UTC, alex-sus commented on app/src/main/res/layout/fragment_contact_list.xml
> +    android:orientation="vertical">
Потому что до этого он побывал линеар лайаутом. Убрал.
Сделано

2021-04-12 22:02 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactItemDecoration.kt
> +            if (childAdapterPosition == adapter.itemCount - 1) outRect.bottom = 0
Сделано

2021-04-12 22:02 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    private class DiffCallback : DiffUtil.ItemCallback<BriefContact>() {
Сделано

2021-04-12 22:02 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +    inner class ContactViewHolder(var contactRow: ContactListRowBinding)
Сделано

2021-04-12 22:02 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +                navigateCallback?.navigateToContactDetailsFragment(item.id)
Сделано

2021-04-13 06:50 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(val navigateCallback: OnContactListCallback?)
Ладно. С утра на свежую голову я понял, чего ты хотел и сделал это. Функции высшего порядка и т.д и т.п.

2021-04-13 09:54 UTC, KalimullinIlnaz requested changes

2021-04-13 09:54 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(private val navigateTo: (String) -> Unit) :
сделай форматирование аналогичное ContactViewHolder

2021-04-13 09:54 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +            )
```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int) = ContactViewHolder(
                    ContactListRowBinding .inflate(LayoutInflater.from(parent.context), parent, false),
                    navigateTo
            )
```
и именованные аргументы

2021-04-13 09:54 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +                        filteredList.postValue(filteredList.value?.filter {
согласен
тогда переносим все операции фильтрации на default диспатчер, io предназначен для операций ввода и вывода

2021-04-13 11:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/viewmodel/ContactListViewModel.kt
> +                        filteredList.postValue(filteredList.value?.filter {
Сделано

2021-04-13 11:01 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +class ContactListAdapter(private val navigateTo: (String) -> Unit) :
Сделано

2021-04-13 11:02 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +            )
Сделано

2021-04-13 16:54 UTC, KalimullinIlnaz requested changes

2021-04-13 16:54 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +                navigateTo(item.id)
проверка на RecyclerView.NO_POSITION должна быть здесь, то есть вызов  navigateTo(item.id) должен быть обернут в этот if

2021-04-13 16:56 UTC, KalimullinIlnaz commented
Также вижу, что у тебя в этом коммите изменения из прошлого задания, так быть не должно, в этом коммите должны быть только изменения по этому заданию

2021-04-13 17:49 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +                navigateTo(item.id)
Не понял. Эта функция bind() вызывается только в onBindViewHolder, а там уже стоит проверка на RecyclerView.NO_POSITION, зачем проверять второй раз одно и то же?
И чтобы проверить на RecyclerView.NO_POSITION нужен position, а откуда его взять в bind() ?

2021-04-13 17:52 UTC, alex-sus commented
> Также вижу, что у тебя в этом коммите изменения из прошлого задания, так быть не должно, в этом коммите должны быть только изменения по этому заданию

Это где, не понимаю

2021-04-13 18:15 UTC, KalimullinIlnaz commented
Открой files changed, там у тебя viewmodel-ки добавились и тп, даже в том же readme файле, добавилось два пункта 6 и 7, а не только 7

2021-04-13 18:21 UTC, KalimullinIlnaz commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +                navigateTo(item.id)
в метоже bind просто напиши adapterPosition
в onBindViewHolder не нужна проверка

2021-04-13 18:24 UTC, KalimullinIlnaz commented
Ещё раз как должен выглядеть процесс выведения ветки
1. смержили предыдущий мр с main
2. чекаут на main
3. из main вывели новую ветку
похоже я не доглядел

2021-04-13 18:37 UTC, alex-sus commented on app/src/main/java/ru/yodata/app65/view/ContactListAdapter.kt
> +                navigateTo(item.id)
Сделано

2021-04-13 18:41 UTC, alex-sus commented
> Ещё раз как должен выглядеть процесс выведения ветки
> 
> 1. смержили предыдущий мр с main
> 2. чекаут на main
> 3. из main вывели новую ветку
>    похоже я не доглядел

Я так и делал. 
Не понимаю, что за ерунда. Эти изменения я точно сделал еще в прошлый раз - и readme и репозиторий переименовал

2021-04-13 18:44 UTC, KalimullinIlnaz commented
![image](https://user-images.githubusercontent.com/63044917/114604230-b7ae6d80-9ca9-11eb-87f1-7c3e5aac7d39.png)
выглядит будто ты смержил, но вывел из коммита прошлого мерж реквеста

2021-04-13 19:35 UTC, KalimullinIlnaz approved these changes

2021-04-13 19:35 UTC, merged